### ISSUE TITLE
Adapter Disconnects when trying to do OTA

### ISSUE THREAD

**Issue by ReviloEgros** [Nerivec/silabs-firmware-builder#24]
Hello,

i can't do any OTA with my zbdongle-e. The adapter still disconnects with FATAL ERROR. I am using firmware 8.0.2.0 and found this comment [https://github.com/Koenkk/zigbee2mqtt/discussions/23224#discussioncomment-10422347](url). But i can't download the max firmware because github tells me it is expired and has no download links. Would it be possible to post a max firmware based on version 8.0.2.0?

**Comment by Nerivec** [comment]
New firmware releases are available here https://github.com/Nerivec/silabs-firmware-builder/releases

Note: That issue you have may be related to https://github.com/Koenkk/zigbee2mqtt/issues/23861 (being investigated). If the new firmware doesn't solve your problem, I suggest you follow that thread for progress and close this one.
