### ISSUE TITLE
LQI signal strength 0 after updating Sonoff ZBDongle-E to 8.0.1

### ISSUE THREAD

**Issue by quensen** [Nerivec/silabs-firmware-builder#3]
I updated my _ITEAD SONOFF Zigbee 3.0 USB Dongle Plus V2_ to firmware `sonoff_zbdonglee_ncp-uart-sw_115200_8.0.1.0.gbl` from `https://github.com/Nerivec/silabs-firmware-builder/releases/tag/v2024.6.1`.
Since then, all newly received signal strengths show 0 LQI.
![image](https://github.com/user-attachments/assets/0aa1ac5c-de42-4e5c-89a0-f36787f86ec9)
![image](https://github.com/user-attachments/assets/ad457160-25d0-4cfc-9eb2-b80ceb50a354)

After switching back to 7.4.3.0 (`ncp-uart-hw-v7.4.3.0-zbdonglee-230400.gbl`) everything is back to normal.
![image](https://github.com/user-attachments/assets/fa97c89c-6e10-4d7e-821d-250868ef8324)

**Comment by Nerivec** [comment]
As mentioned [here](https://github.com/Koenkk/zigbee2mqtt/discussions/23224#discussion-6887141), LQI reporting in messages is currently broken in-firmware. It should be fine in the network map however. Silabs was notified.

**Comment by Nerivec** [comment]
Should be fixed in 8.0.2.
